module.exports = {
  "3g2": "video/3gpp2",
  "3gp": "video/3gpp",
  "3gpp": "audio/3gpp",
  "3mf": "model/3mf",
  "aac": "audio/aac",
  "ac": "application/pkix-attr-cert",
  "adp": "audio/adpcm",
  "adts": "audio/aac",
  "ai": "application/postscript",
  "aml": "application/automationml-aml+xml; charset=utf-8",
  "amlx": "application/automationml-amlx+zip",
  "amr": "audio/amr",
  "apng": "image/apng",
  "appcache": "text/cache-manifest; charset=utf-8",
  "appinstaller": "application/appinstaller",
  "appx": "application/appx",
  "appxbundle": "application/appxbundle",
  "asc": "application/pgp-keys",
  "atom": "application/atom+xml; charset=utf-8",
  "atomcat": "application/atomcat+xml; charset=utf-8",
  "atomdeleted": "application/atomdeleted+xml; charset=utf-8",
  "atomsvc": "application/atomsvc+xml; charset=utf-8",
  "au": "audio/basic",
  "avci": "image/avci",
  "avcs": "image/avcs",
  "avif": "image/avif",
  "aw": "application/applixware",
  "bdoc": "application/bdoc",
  "bin": "application/octet-stream",
  "bmp": "image/bmp",
  "bpk": "application/octet-stream",
  "buffer": "application/octet-stream",
  "ccxml": "application/ccxml+xml; charset=utf-8",
  "cdfx": "application/cdfx+xml; charset=utf-8",
  "cdmia": "application/cdmi-capability",
  "cdmic": "application/cdmi-container",
  "cdmid": "application/cdmi-domain",
  "cdmio": "application/cdmi-object",
  "cdmiq": "application/cdmi-queue",
  "cer": "application/pkix-cert",
  "cgm": "image/cgm",
  "cjs": "application/node; charset=utf-8",
  "class": "application/java-vm",
  "coffee": "text/coffeescript; charset=utf-8",
  "conf": "text/plain; charset=utf-8",
  "cpl": "application/cpl+xml; charset=utf-8",
  "cpt": "application/mac-compactpro",
  "crl": "application/pkix-crl",
  "css": "text/css; charset=utf-8",
  "csv": "text/csv; charset=utf-8",
  "cu": "application/cu-seeme",
  "cwl": "application/cwl",
  "davmount": "application/davmount+xml; charset=utf-8",
  "dbk": "application/docbook+xml; charset=utf-8",
  "deb": "application/octet-stream",
  "def": "text/plain; charset=utf-8",
  "deploy": "application/octet-stream",
  "dib": "image/bmp",
  "disposition-notification": "message/disposition-notification",
  "dist": "application/octet-stream",
  "distz": "application/octet-stream",
  "dll": "application/octet-stream",
  "dmg": "application/octet-stream",
  "dms": "application/octet-stream",
  "doc": "application/msword",
  "dot": "application/msword",
  "dpx": "image/dpx",
  "drle": "image/dicom-rle",
  "dssc": "application/dssc+der",
  "dtd": "application/xml-dtd",
  "dump": "application/octet-stream",
  "dwd": "application/atsc-dwd+xml; charset=utf-8",
  "ear": "application/java-archive",
  "ecma": "application/ecmascript",
  "elc": "application/octet-stream",
  "emf": "image/emf",
  "eml": "message/rfc822",
  "emma": "application/emma+xml; charset=utf-8",
  "emotionml": "application/emotionml+xml; charset=utf-8",
  "eps": "application/postscript",
  "epub": "application/epub+zip",
  "exe": "application/octet-stream",
  "exi": "application/exi",
  "exp": "application/express",
  "exr": "image/aces",
  "ez": "application/andrew-inset",
  "fdf": "application/fdf",
  "fdt": "application/fdt+xml; charset=utf-8",
  "fits": "image/fits",
  "g3": "image/g3fax",
  "gbr": "application/rpki-ghostbusters",
  "geojson": "application/geo+json; charset=utf-8",
  "gif": "image/gif",
  "glb": "model/gltf-binary",
  "gltf": "model/gltf+json; charset=utf-8",
  "gml": "application/gml+xml; charset=utf-8",
  "gpx": "application/gpx+xml; charset=utf-8",
  "gram": "application/srgs",
  "grxml": "application/srgs+xml; charset=utf-8",
  "gxf": "application/gxf",
  "gz": "application/gzip",
  "h261": "video/h261",
  "h263": "video/h263",
  "h264": "video/h264",
  "heic": "image/heic",
  "heics": "image/heic-sequence",
  "heif": "image/heif",
  "heifs": "image/heif-sequence",
  "hej2": "image/hej2k",
  "held": "application/atsc-held+xml; charset=utf-8",
  "hjson": "application/hjson",
  "hlp": "application/winhlp",
  "hqx": "application/mac-binhex40",
  "hsj2": "image/hsj2",
  "htm": "text/html; charset=utf-8",
  "html": "text/html; charset=utf-8",
  "ics": "text/calendar; charset=utf-8",
  "ief": "image/ief",
  "ifb": "text/calendar; charset=utf-8",
  "iges": "model/iges",
  "igs": "model/iges",
  "img": "application/octet-stream",
  "in": "text/plain; charset=utf-8",
  "ini": "text/plain; charset=utf-8",
  "ink": "application/inkml+xml; charset=utf-8",
  "inkml": "application/inkml+xml; charset=utf-8",
  "ipfix": "application/ipfix",
  "iso": "application/octet-stream",
  "its": "application/its+xml; charset=utf-8",
  "jade": "text/jade; charset=utf-8",
  "jar": "application/java-archive",
  "jhc": "image/jphc",
  "jls": "image/jls",
  "jp2": "image/jp2",
  "jpe": "image/jpeg",
  "jpeg": "image/jpeg",
  "jpf": "image/jpx",
  "jpg": "image/jpeg",
  "jpg2": "image/jp2",
  "jpgm": "image/jpm",
  "jpgv": "video/jpeg",
  "jph": "image/jph",
  "jpm": "image/jpm",
  "jpx": "image/jpx",
  "js": "application/javascript; charset=utf-8",
  "json": "application/json; charset=utf-8",
  "json5": "application/json5; charset=utf-8",
  "jsonld": "application/ld+json; charset=utf-8",
  "jsonml": "application/jsonml+json; charset=utf-8",
  "jsx": "text/jsx; charset=utf-8",
  "jt": "model/jt",
  "jxr": "image/jxr",
  "jxra": "image/jxra",
  "jxrs": "image/jxrs",
  "jxs": "image/jxs",
  "jxsc": "image/jxsc",
  "jxsi": "image/jxsi",
  "jxss": "image/jxss",
  "kar": "audio/midi",
  "ktx": "image/ktx",
  "ktx2": "image/ktx2",
  "less": "text/less; charset=utf-8",
  "lgr": "application/lgr+xml; charset=utf-8",
  "list": "text/plain; charset=utf-8",
  "litcoffee": "text/coffeescript; charset=utf-8",
  "log": "text/plain; charset=utf-8",
  "lostxml": "application/lost+xml; charset=utf-8",
  "lrf": "application/octet-stream",
  "m1v": "video/mpeg",
  "m21": "application/mp21",
  "m2a": "audio/mpeg",
  "m2v": "video/mpeg",
  "m3a": "audio/mpeg",
  "m4a": "audio/mp4",
  "m4p": "application/mp4",
  "m4s": "video/iso.segment",
  "ma": "application/mathematica",
  "mads": "application/mads+xml; charset=utf-8",
  "maei": "application/mmt-aei+xml; charset=utf-8",
  "man": "text/troff; charset=utf-8",
  "manifest": "text/cache-manifest; charset=utf-8",
  "map": "application/json; charset=utf-8",
  "mar": "application/octet-stream",
  "markdown": "text/markdown; charset=utf-8",
  "mathml": "application/mathml+xml; charset=utf-8",
  "mb": "application/mathematica",
  "mbox": "application/mbox",
  "md": "text/markdown; charset=utf-8",
  "mdx": "text/mdx; charset=utf-8",
  "me": "text/troff; charset=utf-8",
  "mesh": "model/mesh",
  "meta4": "application/metalink4+xml; charset=utf-8",
  "metalink": "application/metalink+xml; charset=utf-8",
  "mets": "application/mets+xml; charset=utf-8",
  "mft": "application/rpki-manifest",
  "mid": "audio/midi",
  "midi": "audio/midi",
  "mime": "message/rfc822",
  "mj2": "video/mj2",
  "mjp2": "video/mj2",
  "mjs": "text/javascript; charset=utf-8",
  "mml": "text/mathml; charset=utf-8",
  "mods": "application/mods+xml; charset=utf-8",
  "mov": "video/quicktime",
  "mp2": "audio/mpeg",
  "mp21": "application/mp21",
  "mp2a": "audio/mpeg",
  "mp3": "audio/mp3",
  "mp4": "application/mp4",
  "mp4a": "audio/mp4",
  "mp4s": "application/mp4",
  "mp4v": "video/mp4",
  "mpd": "application/dash+xml; charset=utf-8",
  "mpe": "video/mpeg",
  "mpeg": "video/mpeg",
  "mpf": "application/media-policy-dataset+xml; charset=utf-8",
  "mpg": "video/mpeg",
  "mpg4": "application/mp4",
  "mpga": "audio/mpeg",
  "mpp": "application/dash-patch+xml; charset=utf-8",
  "mrc": "application/marc",
  "mrcx": "application/marcxml+xml; charset=utf-8",
  "ms": "text/troff; charset=utf-8",
  "mscml": "application/mediaservercontrol+xml; charset=utf-8",
  "msh": "model/mesh",
  "msi": "application/octet-stream",
  "msix": "application/msix",
  "msixbundle": "application/msixbundle",
  "msm": "application/octet-stream",
  "msp": "application/octet-stream",
  "mtl": "model/mtl",
  "musd": "application/mmt-usd+xml; charset=utf-8",
  "mxf": "application/mxf",
  "mxmf": "audio/mobile-xmf",
  "mxml": "application/xv+xml; charset=utf-8",
  "n3": "text/n3; charset=utf-8",
  "nb": "application/mathematica",
  "nq": "application/n-quads",
  "nt": "application/n-triples",
  "obj": "model/obj",
  "oda": "application/oda",
  "oga": "audio/ogg",
  "ogg": "audio/ogg",
  "ogv": "video/ogg",
  "ogx": "application/ogg",
  "omdoc": "application/omdoc+xml; charset=utf-8",
  "onepkg": "application/onenote",
  "onetmp": "application/onenote",
  "onetoc": "application/onenote",
  "onetoc2": "application/onenote",
  "opf": "application/oebps-package+xml; charset=utf-8",
  "opus": "audio/ogg",
  "otf": "font/otf",
  "owl": "application/rdf+xml; charset=utf-8",
  "oxps": "application/oxps",
  "p10": "application/pkcs10",
  "p7c": "application/pkcs7-mime",
  "p7m": "application/pkcs7-mime",
  "p7s": "application/pkcs7-signature",
  "p8": "application/pkcs8",
  "pdf": "application/pdf",
  "pfr": "application/font-tdpfr",
  "pgp": "application/pgp-encrypted",
  "pkg": "application/octet-stream",
  "pki": "application/pkixcmp",
  "pkipath": "application/pkix-pkipath",
  "pls": "application/pls+xml; charset=utf-8",
  "png": "image/png",
  "prc": "model/prc",
  "prf": "application/pics-rules",
  "provx": "application/provenance+xml; charset=utf-8",
  "ps": "application/postscript",
  "pskcxml": "application/pskc+xml; charset=utf-8",
  "qt": "video/quicktime",
  "raml": "application/raml+yaml; charset=utf-8",
  "rapd": "application/route-apd+xml; charset=utf-8",
  "rdf": "application/rdf+xml; charset=utf-8",
  "relo": "application/p2p-overlay+xml; charset=utf-8",
  "rif": "application/reginfo+xml; charset=utf-8",
  "rl": "application/resource-lists+xml; charset=utf-8",
  "rld": "application/resource-lists-diff+xml; charset=utf-8",
  "rmi": "audio/midi",
  "rnc": "application/relax-ng-compact-syntax",
  "rng": "application/xml; charset=utf-8",
  "roa": "application/rpki-roa",
  "roff": "text/troff; charset=utf-8",
  "rq": "application/sparql-query",
  "rs": "application/rls-services+xml; charset=utf-8",
  "rsat": "application/atsc-rsat+xml; charset=utf-8",
  "rsd": "application/rsd+xml; charset=utf-8",
  "rsheet": "application/urc-ressheet+xml; charset=utf-8",
  "rss": "application/rss+xml; charset=utf-8",
  "rtf": "application/rtf",
  "rtx": "text/richtext; charset=utf-8",
  "rusd": "application/route-usd+xml; charset=utf-8",
  "s3m": "audio/s3m",
  "sbml": "application/sbml+xml; charset=utf-8",
  "scq": "application/scvp-cv-request",
  "scs": "application/scvp-cv-response",
  "sdp": "application/sdp",
  "senmlx": "application/senml+xml; charset=utf-8",
  "sensmlx": "application/sensml+xml; charset=utf-8",
  "ser": "application/java-serialized-object",
  "setpay": "application/set-payment-initiation",
  "setreg": "application/set-registration-initiation",
  "sgi": "image/sgi",
  "sgm": "text/sgml; charset=utf-8",
  "sgml": "text/sgml; charset=utf-8",
  "shex": "text/shex; charset=utf-8",
  "shf": "application/shf+xml; charset=utf-8",
  "shtml": "text/html; charset=utf-8",
  "sieve": "application/sieve",
  "sig": "application/pgp-signature",
  "sil": "audio/silk",
  "silo": "model/mesh",
  "siv": "application/sieve",
  "slim": "text/slim; charset=utf-8",
  "slm": "text/slim; charset=utf-8",
  "sls": "application/route-s-tsid+xml; charset=utf-8",
  "smi": "application/smil+xml; charset=utf-8",
  "smil": "application/smil+xml; charset=utf-8",
  "snd": "audio/basic",
  "so": "application/octet-stream",
  "spdx": "text/spdx; charset=utf-8",
  "spp": "application/scvp-vp-response",
  "spq": "application/scvp-vp-request",
  "spx": "audio/ogg",
  "sql": "application/sql",
  "sru": "application/sru+xml; charset=utf-8",
  "srx": "application/sparql-results+xml; charset=utf-8",
  "ssdl": "application/ssdl+xml; charset=utf-8",
  "ssml": "application/ssml+xml; charset=utf-8",
  "stk": "application/hyperstudio",
  "stl": "model/stl",
  "stpx": "model/step+xml; charset=utf-8",
  "stpxz": "model/step-xml+zip",
  "stpz": "model/step+zip",
  "styl": "text/stylus; charset=utf-8",
  "stylus": "text/stylus; charset=utf-8",
  "svg": "image/svg+xml; charset=utf-8",
  "svgz": "image/svg+xml; charset=utf-8",
  "swidtag": "application/swid+xml; charset=utf-8",
  "t": "text/troff; charset=utf-8",
  "t38": "image/t38",
  "td": "application/urc-targetdesc+xml; charset=utf-8",
  "tei": "application/tei+xml; charset=utf-8",
  "teicorpus": "application/tei+xml; charset=utf-8",
  "text": "text/plain; charset=utf-8",
  "tfi": "application/thraud+xml; charset=utf-8",
  "tfx": "image/tiff-fx",
  "tif": "image/tiff",
  "tiff": "image/tiff",
  "toml": "application/toml; charset=utf-8",
  "tr": "text/troff; charset=utf-8",
  "trig": "application/trig",
  "ts": "video/mp2t",
  "tsd": "application/timestamped-data",
  "tsv": "text/tab-separated-values; charset=utf-8",
  "ttc": "font/collection",
  "ttf": "font/ttf",
  "ttl": "text/turtle; charset=utf-8",
  "ttml": "application/ttml+xml; charset=utf-8",
  "txt": "text/plain; charset=utf-8",
  "u3d": "model/u3d",
  "u8dsn": "message/global-delivery-status",
  "u8hdr": "message/global-headers",
  "u8mdn": "message/global-disposition-notification",
  "u8msg": "message/global",
  "ubj": "application/ubjson",
  "uri": "text/uri-list; charset=utf-8",
  "uris": "text/uri-list; charset=utf-8",
  "urls": "text/uri-list; charset=utf-8",
  "vcard": "text/vcard; charset=utf-8",
  "vrml": "model/vrml",
  "vtt": "text/vtt; charset=utf-8",
  "vxml": "application/voicexml+xml; charset=utf-8",
  "war": "application/java-archive",
  "wasm": "application/wasm",
  "wav": "audio/wav",
  "weba": "audio/webm",
  "webm": "video/webm",
  "webmanifest": "application/manifest+json; charset=utf-8",
  "webp": "image/webp",
  "wgsl": "text/wgsl; charset=utf-8",
  "wgt": "application/widget",
  "wif": "application/watcherinfo+xml; charset=utf-8",
  "wmf": "image/wmf",
  "woff": "font/woff",
  "woff2": "font/woff2",
  "wrl": "model/vrml",
  "wsdl": "application/wsdl+xml; charset=utf-8",
  "wspolicy": "application/wspolicy+xml; charset=utf-8",
  "x3d": "model/x3d+xml; charset=utf-8",
  "x3db": "model/x3d+binary",
  "x3dbz": "model/x3d+binary",
  "x3dv": "model/x3d+vrml",
  "x3dvz": "model/x3d+vrml",
  "x3dz": "model/x3d+xml; charset=utf-8",
  "xaml": "application/xaml+xml; charset=utf-8",
  "xav": "application/xcap-att+xml; charset=utf-8",
  "xca": "application/xcap-caps+xml; charset=utf-8",
  "xcs": "application/calendar+xml; charset=utf-8",
  "xdf": "application/xcap-diff+xml; charset=utf-8",
  "xdssc": "application/dssc+xml; charset=utf-8",
  "xel": "application/xcap-el+xml; charset=utf-8",
  "xenc": "application/xenc+xml; charset=utf-8",
  "xer": "application/patch-ops-error+xml; charset=utf-8",
  "xfdf": "application/xfdf",
  "xht": "application/xhtml+xml; charset=utf-8",
  "xhtml": "application/xhtml+xml; charset=utf-8",
  "xhvml": "application/xv+xml; charset=utf-8",
  "xlf": "application/xliff+xml; charset=utf-8",
  "xm": "audio/xm",
  "xml": "application/xml; charset=utf-8",
  "xns": "application/xcap-ns+xml; charset=utf-8",
  "xop": "application/xop+xml; charset=utf-8",
  "xpl": "application/xproc+xml; charset=utf-8",
  "xsd": "application/xml; charset=utf-8",
  "xsl": "application/xml; charset=utf-8",
  "xslt": "application/xslt+xml; charset=utf-8",
  "xspf": "application/xspf+xml; charset=utf-8",
  "xvm": "application/xv+xml; charset=utf-8",
  "xvml": "application/xv+xml; charset=utf-8",
  "yaml": "text/yaml; charset=utf-8",
  "yang": "application/yang",
  "yin": "application/yin+xml; charset=utf-8",
  "yml": "text/yaml; charset=utf-8",
  "zip": "application/zip"
}